using Desynchronized.TNDBS;
using RimWorld;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
using Verse;

namespace Desynchronized.Interfaces
{
    public class PawnColumnWorker_KnownNewsCount : PawnColumnWorker_Text
    {
        protected override string GetTextFor(Pawn pawn)
        {
            int knownNewsCount = pawn.GetNewsKnowledgeTracker().ListOfAllKnownNews.Count;
            return knownNewsCount.ToString();
        }

        protected override string GetTip(Pawn pawn)
        {
            int countKnown = 0;
            int countForgotten = 0;
            List<TaleNewsReference> knowledgeList = pawn.GetNewsKnowledgeTracker().ListOfAllKnownNews;
            int listCount = knowledgeList.Count;

            for (int i = 0; i < listCount; i++)
            {
                // Expand further
                countKnown++;
            }

            StringBuilder builder = new StringBuilder("Number of known tale-news: ");
            builder.Append(countKnown);
            builder.AppendLine();
            builder.Append("Number of forgotten tale-news: ");
            builder.Append(double.NaN);
            builder.AppendLine("\n");
            builder.Append("New tale-news are generated by the never-ending stream of events, and old, unimportant tale-news are forgotten.");

            return builder.ToString();
        }
    }
}
