using Desynchronized.TNDBS.Extenders;
using Desynchronized.TNDBS.Utilities;
using RimWorld;
using System.Linq;
using System.Text;
using Verse;

namespace Desynchronized.Interfaces
{
    public class PawnColumnWorker_KnownNewsCount : PawnColumnWorker_Text
    {
        private int GetKnownNewsCount(Pawn pawn)
        {
            return pawn.GetNewsKnowledgeTracker().GetAllNonForgottenNewsReferences().Count();
        }

        protected override string GetTextFor(Pawn pawn)
        {
            return GetKnownNewsCount(pawn).ToString();
        }

        protected override string GetTip(Pawn pawn)
        {
            StringBuilder builder = new StringBuilder("Number of known tale-news: ");
            builder.Append(GetKnownNewsCount(pawn));
            builder.AppendLine("\n");
            builder.Append("New tale-news are generated by the never-ending stream of events, and pawns share what they know about them.");

            return builder.ToString();
        }
    }
}
