using Desynchronized.TNDBS;
using RimWorld;
using Verse;

namespace Desynchronized.Handlers
{
    public class Handler_PawnExecuted
    {
        public static void HandlePawnExecuted(Pawn victim, DeathBrutality brutality)
        {
            SendOutNotificationLetter(victim);
            GenerateAndProcessNews(victim, brutality);
        }

        private static void SendOutNotificationLetter(Pawn victim)
        {
            // string letterLabel = "Kidnapped".Translate() + ": " + victim.LabelShortCap;
            // string letterContent = string.Empty;
            // letterContent += "PawnKidnapped".Translate(victim.LabelShort.CapitalizeFirst(), kidnapper.Faction.def.pawnsPlural, kidnapper.Faction.Name, victim.Named("PAWN"));

            Find.LetterStack.ReceiveLetter("Colonist/Guest executed", "Colonist/Guest was executed. Name of Pawn: " + victim.Name, LetterDefOf.NegativeEvent, victim, null, null);
        }

        private static void GenerateAndProcessNews(Pawn victim, DeathBrutality brutality)
        {
            /*
             * Note:
             * Due to Allow Tools giving out thoughts before the kill,
             * we have to add in an additional statement to account for the cases
             * as generated by Allow Tools.
             * Map mapOfOccurence = [Vanilla Cases] ?? [Allow Tool Cases]
             */
            Map mapOfOccurence = victim.Corpse.Map ?? victim.Map;
            TaleNewsPawnDied news = TaleNewsPawnDied.GenerateAsExecution(victim, brutality);

            foreach (Pawn other in PawnsFinder.AllMapsCaravansAndTravelingTransportPods_Alive_FreeColonistsAndPrisoners)
            {
                TaleNewsReference reference = news.CreateReferenceForReceipient(other);
                DesynchronizedMain.TaleNewsDatabaseSystem.LinkNewsReferenceToPawn(reference, other);

                if (other.Map == mapOfOccurence)
                {
                    reference.ActivateNews();
                }
            }
        }
    }
}
