using Desynchronized.TNDBS;
using Desynchronized.TNDBS.Utilities;
using RimWorld;
using Verse;

namespace Desynchronized.Handlers
{
    public class Handler_PawnExecuted
    {
        public static void HandlePawnExecuted(Pawn victim, DeathBrutality brutality)
        {
            SendOutNotificationLetter(victim);
            GenerateAndProcessNews(victim, brutality);
        }

        private static void SendOutNotificationLetter(Pawn victim)
        {
            // string letterLabel = "Kidnapped".Translate() + ": " + victim.LabelShortCap;
            // string letterContent = string.Empty;
            // letterContent += "PawnKidnapped".Translate(victim.LabelShort.CapitalizeFirst(), kidnapper.Faction.def.pawnsPlural, kidnapper.Faction.Name, victim.Named("PAWN"));

            Find.LetterStack.ReceiveLetter("Colonist/Guest executed", "Colonist/Guest was executed. Name of Pawn: " + victim.Name, LetterDefOf.NegativeEvent, victim, null, null);
        }

        private static void GenerateAndProcessNews(Pawn victim, DeathBrutality brutality)
        {
            /*
             * Note:
             * Due to Allow Tools giving out thoughts before the kill,
             * we have to add in an additional statement to account for the cases
             * as generated by Allow Tools.
             * Map mapOfOccurence = [Allow Tool Cases] ?? [Vanilla Cases];
             * Even though vanilla cases are more common, placing them at the front
             * will result in rather clumsy code. See for yourself.
             */
            Map mapOfOccurence = victim.Map ?? victim.Corpse.Map;
            if (mapOfOccurence == null)
            {
                return;
            }

            TaleNewsPawnDied executionNews = TaleNewsPawnDied.GenerateAsExecution(victim, brutality);

            foreach (Pawn other in PawnsFinder.AllMapsCaravansAndTravelingTransportPods_Alive_FreeColonistsAndPrisoners)
            {
                if (other.Map == mapOfOccurence)
                {
                    other.GetNewsKnowledgeTracker().KnowNews(executionNews, WitnessShockGrade.UNDEFINED);
                }
            }
        }
    }
}
